-- MySQL Script generated by MySQL Workbench
-- qui 11 dez 2025 10:51:12
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sce_bd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sce_bd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sce_bd` ;
USE `sce_bd` ;

-- -----------------------------------------------------
-- Table `sce_bd`.`tipo_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sce_bd`.`tipo_usuario` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `modulo_admin` VARCHAR(1) NOT NULL,
  `modulo_estoque` VARCHAR(1) NOT NULL,
  `modulo_fornecedores` VARCHAR(1) NOT NULL,
  `modulo_movimentacoes` VARCHAR(1) NOT NULL,
  `modulo_compras` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sce_bd`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sce_bd`.`usuarios` (
  `id` INT NOT NULL,
  `nome` VARCHAR(50) NULL,
  `cpf` VARCHAR(15) NULL,
  `senha` VARCHAR(150) NOT NULL,
  `email` VARCHAR(250) NULL,
  `tipo_usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuarios_tipo_usuario_idx` (`tipo_usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuarios_tipo_usuario`
    FOREIGN KEY (`tipo_usuario_id`)
    REFERENCES `sce_bd`.`tipo_usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sce_bd`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sce_bd`.`categorias` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sce_bd`.`fornecedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sce_bd`.`fornecedores` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `cnpj` VARCHAR(20) NULL,
  `telefone` VARCHAR(20) NULL,
  `endereco` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sce_bd`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sce_bd`.`produtos` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(200) NOT NULL,
  `valor` FLOAT NOT NULL,
  `qtdd_estoque` INT NULL,
  `categorias_id` INT NOT NULL,
  `fornecedores_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_produtos_categorias1_idx` (`categorias_id` ASC) VISIBLE,
  INDEX `fk_produtos_fornecedores1_idx` (`fornecedores_id` ASC) VISIBLE,
  CONSTRAINT `fk_produtos_categorias1`
    FOREIGN KEY (`categorias_id`)
    REFERENCES `sce_bd`.`categorias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produtos_fornecedores1`
    FOREIGN KEY (`fornecedores_id`)
    REFERENCES `sce_bd`.`fornecedores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sce_bd`.`movimentacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sce_bd`.`movimentacoes` (
  `id` INT NOT NULL,
  `tipo` ENUM("entrada", "saida") NOT NULL,
  `qttd` INT NOT NULL,
  `observacao` VARCHAR(200) NULL,
  `usuarios_id` INT NOT NULL,
  `produtos_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_movimentacoes_usuarios1_idx` (`usuarios_id` ASC) VISIBLE,
  INDEX `fk_movimentacoes_produtos1_idx` (`produtos_id` ASC) VISIBLE,
  CONSTRAINT `fk_movimentacoes_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `sce_bd`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movimentacoes_produtos1`
    FOREIGN KEY (`produtos_id`)
    REFERENCES `sce_bd`.`produtos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `sce_bd`.`tipo_usuario`
-- -----------------------------------------------------
START TRANSACTION;
USE `sce_bd`;
INSERT INTO `sce_bd`.`tipo_usuario` (`id`, `nome`, `modulo_admin`, `modulo_estoque`, `modulo_fornecedores`, `modulo_movimentacoes`, `modulo_compras`) VALUES (1024, 'admin', 'S', 'S', 'S', 'S', 'S');

COMMIT;


-- -----------------------------------------------------
-- Data for table `sce_bd`.`usuarios`
-- -----------------------------------------------------
START TRANSACTION;
USE `sce_bd`;
INSERT INTO `sce_bd`.`usuarios` (`id`, `nome`, `cpf`, `senha`, `email`, `tipo_usuario_id`) VALUES (1024, 'admin', NULL, 'cbfb296f4c8a4035741cf74cadc294b8cb2b66dc21497443d6267897ce9e10cb1b27d62667e2cf92be9ca7bac9c483130b7d896361d4c09dfa6202b20b5463c8', NULL, 1024);

COMMIT;

